CREATE TABLE "User" ("id" TEXT NOT NULL,"name" TEXT,"email" TEXT,"emailVerified" TIMESTAMP(3),"image" TEXT,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TemplatePreferences" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"facebookTemplate" TEXT NOT NULL,"instagramTemplate" TEXT NOT NULL,"youtubeTemplate" TEXT NOT NULL,"sharedPostscript" TEXT NOT NULL,CONSTRAINT "TemplatePreferences_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Video" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"fileName" TEXT NOT NULL,"s3Url" TEXT,"s3Key" TEXT,"videoTitle" TEXT NOT NULL,"sharedDescription" TEXT NOT NULL,"facebookTemplate" TEXT NOT NULL,"instagramTemplate" TEXT NOT NULL,"youtubeTemplate" TEXT NOT NULL,"blueskyTemplate" TEXT NOT NULL,"twitterTemplate" TEXT NOT NULL,"transcript" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Video_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VideoFeed" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"sourceUrl" TEXT NOT NULL,"sourceType" TEXT NOT NULL,"pollingInterval" INTEGER NOT NULL,"lastCheckedAt" TIMESTAMP(3),"lastVideoId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "VideoFeed_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Account" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"type" TEXT NOT NULL,"provider" TEXT NOT NULL,"providerAccountId" TEXT NOT NULL,"access_token" TEXT,"expires_at" INTEGER,"id_token" TEXT,"refresh_token" TEXT,"scope" TEXT,"session_state" TEXT,"token_type" TEXT,CONSTRAINT "Account_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL,"sessionToken" TEXT NOT NULL,"userId" TEXT NOT NULL,"expires" TIMESTAMP(3) NOT NULL,CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "TemplatePreferences_userId_key" ON "TemplatePreferences"("userId");
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");
ALTER TABLE "TemplatePreferences" ADD CONSTRAINT "TemplatePreferences_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Video" ADD CONSTRAINT "Video_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Video" ADD COLUMN "approvedForSplicing" BOOLEAN NOT NULL DEFAULT false;
CREATE TABLE "FeedVideo" ("id" TEXT NOT NULL,"feedId" TEXT NOT NULL,"videoId" TEXT NOT NULL,"title" TEXT NOT NULL,"s3Url" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "FeedVideo_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "FeedVideo_feedId_videoId_key" ON "FeedVideo"("feedId", "videoId");
ALTER TABLE "FeedVideo" ADD CONSTRAINT "FeedVideo_feedId_fkey" FOREIGN KEY ("feedId") REFERENCES "VideoFeed"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FeedVideo" ADD COLUMN "transcript" TEXT;
ALTER TABLE "FeedVideo" ADD COLUMN "transcriptJson" JSONB;
ALTER TABLE "Video" ADD COLUMN "sourceVideoId" TEXT;
ALTER TABLE "Video" ADD CONSTRAINT "Video_sourceVideoId_fkey" FOREIGN KEY ("sourceVideoId") REFERENCES "Video"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Video" ALTER COLUMN "fileName" DROP NOT NULL;
ALTER TABLE "VideoFeed" ADD COLUMN "userId" TEXT DEFAULT '8d26afd8-2507-4ad0-b113-ddb7440ce732';
ALTER TABLE "FeedVideo" ADD COLUMN "userId" TEXT DEFAULT '8d26afd8-2507-4ad0-b113-ddb7440ce732';
UPDATE "VideoFeed" SET "userId" = '8d26afd8-2507-4ad0-b113-ddb7440ce732' WHERE "userId" IS NULL;
UPDATE "FeedVideo" SET "userId" = '8d26afd8-2507-4ad0-b113-ddb7440ce732' WHERE "userId" IS NULL;
ALTER TABLE "VideoFeed" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "VideoFeed" ALTER COLUMN "userId" DROP DEFAULT;
ALTER TABLE "FeedVideo" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "FeedVideo" ALTER COLUMN "userId" DROP DEFAULT;
ALTER TABLE "VideoFeed" ADD CONSTRAINT "VideoFeed_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FeedVideo" ADD CONSTRAINT "FeedVideo_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "User" ADD COLUMN "stripeCustomerId" TEXT;
ALTER TABLE "User" ADD COLUMN "subscriptionPlan" TEXT NOT NULL DEFAULT 'free';
CREATE TABLE "Transcription" ("id" TEXT NOT NULL,"fileName" TEXT NOT NULL,"transcript" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Transcription_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Segment" ("id" TEXT NOT NULL,"videoId" TEXT NOT NULL,"tStartS" DOUBLE PRECISION NOT NULL,"tEndS" DOUBLE PRECISION NOT NULL,"features" JSONB NOT NULL,"llmNotes" JSONB,"score" DOUBLE PRECISION NOT NULL,"selected" BOOLEAN NOT NULL DEFAULT false,CONSTRAINT "Segment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Clip" ("id" TEXT NOT NULL,"segmentId" TEXT NOT NULL,"variant" TEXT NOT NULL,"s3Key" TEXT,"title" TEXT,"description" TEXT,"hashtags" TEXT,"publishMap" JSONB,CONSTRAINT "Clip_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Metric" ("id" TEXT NOT NULL,"clipId" TEXT NOT NULL,"platform" TEXT NOT NULL,"impressions" INTEGER NOT NULL,"views3s" INTEGER NOT NULL,"views30s" INTEGER NOT NULL,"avgWatchS" DOUBLE PRECISION NOT NULL,"ctr" DOUBLE PRECISION NOT NULL,"collectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Metric_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Segment_videoId_idx" ON "Segment"("videoId");
CREATE INDEX "Segment_score_idx" ON "Segment"("score");
CREATE INDEX "Clip_segmentId_idx" ON "Clip"("segmentId");
CREATE INDEX "Metric_clipId_idx" ON "Metric"("clipId");
ALTER TABLE "Segment" ADD CONSTRAINT "Segment_videoId_fkey" FOREIGN KEY ("videoId") REFERENCES "Video"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Clip" ADD CONSTRAINT "Clip_segmentId_fkey" FOREIGN KEY ("segmentId") REFERENCES "Segment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Metric" ADD CONSTRAINT "Metric_clipId_fkey" FOREIGN KEY ("clipId") REFERENCES "Clip"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "VideoFeed" ADD COLUMN "autoGenerateClips" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "VideoFeed" ADD COLUMN "viralitySettings" JSONB;
ALTER TABLE "FeedVideo" ADD COLUMN "thumbnailUrl" TEXT;
CREATE TABLE "SegmentRhetoricLabel" ("id" TEXT NOT NULL,"segmentId" TEXT NOT NULL,"label" DOUBLE PRECISION NOT NULL,"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SegmentRhetoricLabel_pkey" PRIMARY KEY ("id"));
CREATE INDEX "SegmentRhetoricLabel_segmentId_idx" ON "SegmentRhetoricLabel"("segmentId");
ALTER TABLE "SegmentRhetoricLabel" ADD CONSTRAINT "SegmentRhetoricLabel_segmentId_fkey" FOREIGN KEY ("segmentId") REFERENCES "Segment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FeedVideo" ADD COLUMN "clipSourceVideoId" TEXT;
CREATE UNIQUE INDEX "FeedVideo_clipSourceVideoId_key" ON "FeedVideo"("clipSourceVideoId");
ALTER TABLE "FeedVideo" ADD CONSTRAINT "FeedVideo_clipSourceVideoId_fkey" FOREIGN KEY ("clipSourceVideoId") REFERENCES "Video"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultLLMProvider" TEXT NOT NULL DEFAULT 'gemini';
ALTER TABLE "FeedVideo" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ready';
ALTER TABLE "User" ALTER COLUMN "defaultLLMProvider" SET DEFAULT 'ollama';
DROP TABLE "Transcription";
CREATE TABLE "ClipCropTemplate" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"aspectRatio" TEXT NOT NULL,"cropX" DOUBLE PRECISION NOT NULL,"cropY" DOUBLE PRECISION NOT NULL,"cropWidth" DOUBLE PRECISION NOT NULL,"cropHeight" DOUBLE PRECISION NOT NULL,"isDefault" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ClipCropTemplate_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ClipCropTemplate_userId_idx" ON "ClipCropTemplate"("userId");
CREATE UNIQUE INDEX "ClipCropTemplate_userId_name_key" ON "ClipCropTemplate"("userId", "name");
ALTER TABLE "ClipCropTemplate" ADD CONSTRAINT "ClipCropTemplate_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Video" ADD COLUMN "trimStartS" DOUBLE PRECISION;
ALTER TABLE "Video" ADD COLUMN "trimEndS" DOUBLE PRECISION;
